# SPDX-License-Identifier: MIT-0
---
# install using dnf

- name: Import gpg public key
  ansible.builtin.get_url:
    url: "{{ mvk_subl_server }}/{{ mvk_subl_apt_key }}"
    dest: "{{ mvk_subl_apt_key_path }}"
    mode: '0440'
  become: true

- name: Create repository sources file
  ansible.builtin.template:
    src: "{{ ansible_pkg_mgr }}/{{ item }}.j2"
    dest: "/{{ item }}"
    owner: root
    group: root
    mode: '0644'
  loop:
    - "{{ mvk_subl_apt_repo_path }}"
  become: true


- name: Install package sublime-text
  ansible.builtin.apt:
    name: "{{ mvk_subl_dnf_package }}"
    state: present
    update_cache: true
  become: true
